<?php

namespace ContainerMxoSsfx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HisUi5zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hisUi5z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hisUi5z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\BlogController::delete' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\BlogController::edit' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\CommentController::blog' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\CommentController::post' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\InterestController::delete' => ['privates', '.service_locator.47vzlea', 'get_ServiceLocator_47vzleaService', true],
            'App\\Controller\\InterestController::edit' => ['privates', '.service_locator.47vzlea', 'get_ServiceLocator_47vzleaService', true],
            'App\\Controller\\MessageController::message' => ['privates', '.service_locator.O3A1vmO', 'get_ServiceLocator_O3A1vmOService', true],
            'App\\Controller\\RegistrationController::login' => ['privates', '.service_locator.pV4I0RO', 'get_ServiceLocator_PV4I0ROService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BlogController:delete' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\BlogController:edit' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\CommentController:blog' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\CommentController:post' => ['privates', '.service_locator..TQcBti', 'get_ServiceLocator__TQcBtiService', true],
            'App\\Controller\\InterestController:delete' => ['privates', '.service_locator.47vzlea', 'get_ServiceLocator_47vzleaService', true],
            'App\\Controller\\InterestController:edit' => ['privates', '.service_locator.47vzlea', 'get_ServiceLocator_47vzleaService', true],
            'App\\Controller\\MessageController:message' => ['privates', '.service_locator.O3A1vmO', 'get_ServiceLocator_O3A1vmOService', true],
            'App\\Controller\\RegistrationController:login' => ['privates', '.service_locator.pV4I0RO', 'get_ServiceLocator_PV4I0ROService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BlogController::delete' => '?',
            'App\\Controller\\BlogController::edit' => '?',
            'App\\Controller\\CommentController::blog' => '?',
            'App\\Controller\\CommentController::post' => '?',
            'App\\Controller\\InterestController::delete' => '?',
            'App\\Controller\\InterestController::edit' => '?',
            'App\\Controller\\MessageController::message' => '?',
            'App\\Controller\\RegistrationController::login' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BlogController:delete' => '?',
            'App\\Controller\\BlogController:edit' => '?',
            'App\\Controller\\CommentController:blog' => '?',
            'App\\Controller\\CommentController:post' => '?',
            'App\\Controller\\InterestController:delete' => '?',
            'App\\Controller\\InterestController:edit' => '?',
            'App\\Controller\\MessageController:message' => '?',
            'App\\Controller\\RegistrationController:login' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
