<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Profile extends \App\Entity\Profile implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'bio' => [parent::class, 'bio', null],
        "\0".parent::class."\0".'blogs' => [parent::class, 'blogs', null],
        "\0".parent::class."\0".'comments' => [parent::class, 'comments', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imageUrl' => [parent::class, 'imageUrl', null],
        "\0".parent::class."\0".'interests' => [parent::class, 'interests', null],
        "\0".parent::class."\0".'intro' => [parent::class, 'intro', null],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null],
        "\0".parent::class."\0".'messages_received' => [parent::class, 'messages_received', null],
        "\0".parent::class."\0".'messages_sent' => [parent::class, 'messages_sent', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'number' => [parent::class, 'number', null],
        "\0".parent::class."\0".'soc_facebook' => [parent::class, 'soc_facebook', null],
        "\0".parent::class."\0".'soc_linkedin' => [parent::class, 'soc_linkedin', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null],
        'bio' => [parent::class, 'bio', null],
        'blogs' => [parent::class, 'blogs', null],
        'comments' => [parent::class, 'comments', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'imageUrl' => [parent::class, 'imageUrl', null],
        'interests' => [parent::class, 'interests', null],
        'intro' => [parent::class, 'intro', null],
        'location' => [parent::class, 'location', null],
        'messages_received' => [parent::class, 'messages_received', null],
        'messages_sent' => [parent::class, 'messages_sent', null],
        'name' => [parent::class, 'name', null],
        'number' => [parent::class, 'number', null],
        'soc_facebook' => [parent::class, 'soc_facebook', null],
        'soc_linkedin' => [parent::class, 'soc_linkedin', null],
        'user' => [parent::class, 'user', null],
        'username' => [parent::class, 'username', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
