<?php

namespace Container3bL3Ll2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInterestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.47vzlea.App\Entity\Interest' shared service.
     *
     * @return \App\Entity\Interest
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.47vzlea": it needs an instance of "App\\Entity\\Interest" but this type has been excluded in "config/services.yaml".');
    }
}
