<?php

namespace Container3bL3Ll2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInterestControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\InterestController' shared autowired service.
     *
     * @return \App\Controller\InterestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/InterestController.php';

        $container->services['App\\Controller\\InterestController'] = $instance = new \App\Controller\InterestController(($container->privates['App\\Repository\\InterestRepository'] ?? $container->load('getInterestRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\InterestController', $container));

        return $instance;
    }
}
