<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxoSsfx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxoSsfx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMxoSsfx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMxoSsfx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMxoSsfx\App_KernelDevDebugContainer([
    'container.build_hash' => 'MxoSsfx',
    'container.build_id' => 'd3e7ce19',
    'container.build_time' => 1713178066,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxoSsfx');
